# Generated by Django 5.2 on 2025-04-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('medio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('portada', models.ImageField(upload_to='portada/')),
                ('visitas', models.PositiveBigIntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medio.medio')),
            ],
        ),
    ]
