# Generated by Django 5.2 on 2025-04-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='portada',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
