# Generated by Django 5.2 on 2025-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_alter_noticia_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(default='Texto por defecto'),
        ),
    ]
