# Generated by Django 5.2 on 2025-04-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_noticia_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='fecha',
        ),
    ]
