# Generated by Django 5.2 on 2025-04-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
