# Generated by Django 5.2.17 on 2026-10-02 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def validate_integrity(apps, schema_editor):
    from urllib.parse import urlsplit, urlunsplit, parse_qsl, urlencode

    news = apps.get_model("noticia", "Noticia")
    images = apps.get_model("noticia", "NoticiaImagen")
    categories = apps.get_model("noticia", "Categoria")
    alias = schema_editor.connection.alias
    normalized = []
    seen = {}
    for pk, medium, url in (
        news.objects.using(alias)
        .exclude(url="")
        .values_list("pk", "medio_id", "url")
        .iterator()
    ):
        try:
            parts = urlsplit(url)
            query = [
                (k, v)
                for k, v in parse_qsl(parts.query, keep_blank_values=True)
                if not k.lower().startswith("utm_")
                and k.lower() not in ("fbclid", "gclid")
            ]
            canonical = urlunsplit(
                (
                    parts.scheme.lower(),
                    parts.netloc.lower(),
                    parts.path or "/",
                    urlencode(sorted(query)),
                    "",
                )
            )
        except ValueError:
            canonical = url
        key = (medium, canonical)
        if key in seen:
            raise RuntimeError(
                f"Noticias duplicadas: IDs {seen[key]} y {pk}. Respaldar y resolver antes de migrar."
            )
        seen[key] = pk
        normalized.append((pk, canonical))
    seen_images = set()
    for article, url in (
        images.objects.using(alias).values_list("noticia_id", "url").iterator()
    ):
        if (article, url) in seen_images:
            raise RuntimeError(
                f"Imágenes duplicadas en noticia {article}. Resolver antes de migrar."
            )
        seen_images.add((article, url))
    seen_categories = set()
    for name in categories.objects.using(alias).values_list("nombre", flat=True):
        if name.strip().upper() in seen_categories:
            raise RuntimeError(
                "Categorías duplicadas al normalizar. Resolver antes de migrar."
            )
        seen_categories.add(name.strip().upper())
    for pk, url in normalized:
        news.objects.using(alias).filter(pk=pk).update(url=url)
    for row in categories.objects.using(alias).all():
        categories.objects.using(alias).filter(pk=row.pk).update(
            nombre=row.nombre.strip().upper()
        )


class Migration(migrations.Migration):

    dependencies = [
        ("medio", "0002_alter_medio_options_alter_medio_categoria_and_more"),
        ("noticia", "0004_noticiaimagen"),
    ]

    operations = [
        migrations.RunPython(validate_integrity, migrations.RunPython.noop),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuente", models.CharField(max_length=40)),
                ("inicio", models.DateTimeField(auto_now_add=True)),
                ("fin", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(default="running", max_length=20)),
                ("detectadas", models.PositiveIntegerField(default=0)),
                ("guardadas", models.PositiveIntegerField(default=0)),
                ("omitidas", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-inicio"],
            },
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterModelOptions(
            name="noticia",
            options={"ordering": ["-fecha", "-id"]},
        ),
        migrations.AddField(
            model_name="noticia",
            name="actualizado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="noticia",
            name="fecha_estimada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="noticia",
            name="fecha_ingesta",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categoria_noticia",
                to="noticia.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="contenido",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="fecha",
            field=models.DateTimeField(verbose_name="Fecha de publicación"),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="medio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="medio.medio"
            ),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="portada",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="noticia",
            name="url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="noticiaimagen",
            name="url",
            field=models.URLField(max_length=2000),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(fields=["-fecha", "-id"], name="noticia_fecha_idx"),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(
                fields=["categoria", "-fecha"], name="noticia_categoria_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="noticia",
            index=models.Index(fields=["medio", "-fecha"], name="noticia_medio_idx"),
        ),
        migrations.AddConstraint(
            model_name="noticia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("url", ""), _negated=True),
                fields=("medio", "url"),
                name="noticia_medio_url_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="noticiaimagen",
            constraint=models.UniqueConstraint(
                fields=("noticia", "url"), name="noticia_imagen_unique"
            ),
        ),
    ]
