# Generated by Django 5.2.17 on 2026-10-02 02:57

from django.db import migrations, models


def validate_media(apps, schema_editor):
    model = apps.get_model("medio", "Medio")
    groups = {}
    for pk, name in model.objects.using(schema_editor.connection.alias).values_list(
        "pk", "nombre"
    ):
        groups.setdefault(name.strip().upper(), []).append(pk)
    duplicates = [ids for ids in groups.values() if len(ids) > 1]
    if duplicates:
        raise RuntimeError(
            "Medios duplicados tras normalizar. Revisar IDs antes de migrar: "
            + str(duplicates[:10])
        )
    for name, ids in groups.items():
        model.objects.using(schema_editor.connection.alias).filter(pk=ids[0]).update(
            nombre=name
        )


class Migration(migrations.Migration):

    dependencies = [
        ("medio", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(validate_media, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="medio",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterField(
            model_name="medio",
            name="categoria",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="medio",
            name="nombre",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
