name: Calidad
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.lock.txt
      - run: python manage.py test --settings=noticias.settings.test
      - run: python manage.py makemigrations --check --dry-run --settings=noticias.settings.test
